export interface PropertyDto extends Array<PropertyDto>{
    propertyId: number,
    companyId: number,
    companyName: string,
    statusId: number,
    typeId: number,
    typeDescription: string,
    buildingName: string,
    erfNumber: string,
    street: string,
    township: string,
    city: string,
    state: string,
    country: string,
    postalCode: string,
    zoning:string,
    grossBuildingArea: number,
    grossLettableArea: number,
    electricitySupply: number,
    roofType: string,
    dateAcquired: Date,
    investicoreShareHolding: number,
    capitalisationRate: number,
    erfSize: number,
    buildingFootprint: number,
    salePrice: number,
    saleDate: Date,
    addressId: number,
    sageId: string,
    purchasePrice: number,
    improvements: number,
    fairValue: number,
    propertyPrice: number,
    propertyManagerId: number,
    propertyManagerName: string
}
